blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/r7ZhAREg2M
    about: You can join our Discord.
  - name: Website
    url: https://opensource.tcetmumbai.in/
    about: Visit for more Information.
